version: "3.8"
services:
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=tp_docker
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tp_docker
      ports: "3306:3306"

  mail:
    restart: always
    environment:
      MH_SMTP_BIND_ADDR: 0.0.0.0:1025
      MH_STORAGE: local
      MH_AUTH: false
    ports:
      - 8025:8025